name: cypress-tests

on: deployment

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/vercel-cypress@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          repo: my-repo